# Generated by Django 6.1 on 2026-08-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_bloodrequest_latitude_bloodrequest_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='sos_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
