# Generated by Django 6.1 on 2026-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_sosalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='current_wave',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
