# Generated by Django 6.1 on 2026-08-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_bloodrequest_current_wave'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_bank_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
