# Generated by Django 6.1 on 2026-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_bloodbankstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodShortageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('required_units', models.PositiveIntegerField()),
                ('available_units', models.PositiveIntegerField()),
                ('shortage_units', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
