# Generated by Django 6.1 on 2026-08-23 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_donationdrive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='college',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'college'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_donors', to=settings.AUTH_USER_MODEL),
        ),
    ]
