# Generated by Django 6.1 on 2026-08-26 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_donorprofile_college'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankstock',
            name='blood_bank',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'blood_bank'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_bank_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationdrive',
            name='college',
            field=models.ForeignKey(limit_choices_to={'role': 'college'}, on_delete=django.db.models.deletion.CASCADE, related_name='donation_drives', to=settings.AUTH_USER_MODEL),
        ),
    ]
